volumes:
  logs:
    driver: local

services:
  slim:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    command: php -S 0.0.0.0:8080 -t public
    environment:
      docker: "true"
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www
    container_name: slim_app
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    ports:
      - "8102:3306"
    container_name: slim_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: gr_test
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./tmp/db:/var/lib/mysql